### ISSUE TITLE
Insert pages created by Thrive Architect

### ISSUE THREAD

**Issue by 360path** [uhm-coe/insert-pages#12]
Trying to insert a page created with Thrive Architect doesn't include its inline generated styles. Probably similar problem with Elementor etc (https://wordpress.org/support/topic/insert-pages-created-by-elementor/)

**Comment by figureone** [comment]
Since Thrive Architect is not open source, I cannot install and test it to create an integration with Insert Pages. You can try opening a support request with them (assuming you purchased a license) to make further progress.

Similar integrations for other builders are here, and I would be willing to merge a pull request for Thrive:
https://github.com/uhm-coe/insert-pages/blob/master/insert-pages.php#L276-L345
