### ISSUE TITLE
How to access plugin via Gutenberg editor

### ISSUE THREAD

**Issue by wemmons53** [uhm-coe/insert-pages#19]
Have the Guetenberg editor on website. How do I access the insert button? Your screenshots show old classic editor.

**Comment by figureone** [comment]
Currently the only Gutenberg integration is to use the Shortcode block and type in the shortcode manually, e.g., `[insert page="sample-page" display="content"]`.

Since WordPress now includes Reusable Blocks by default, we assumed this plugin would sunset, but other users have explained use cases where an Insert Page block would still be useful. We do plan on releasing a block eventually, and will be tracking progress here:
https://wordpress.org/support/topic/gutenberg-read/
