### ISSUE TITLE
[improvement] - add custom post type templates from plugins, not just theme / theme-compat

### ISSUE THREAD

**Issue by HongPong** [uhm-coe/insert-pages#58]
Would like to load templates from inside a plugin, for the sake of feature organization. Of course this doesn't mean everything works as it should...

per insert_pages_handle_shortcode_insert ln 1018, it tries not to allow templates all over the system, which is sensible. locate_template() is pretty restrictive. I have been using require statements to get around this.

Also filter insert_pages_available_templates could maybe be used I think, just wanted to mention that. Didn't see how to deal with it though. I tried adding a reference to the template into filters theme_CPTSLUG_templates, and CPTSLUG_template , and it did not get picked up. I've been thrashing around with these template loaders earlier, not just re this .. I may definitely be missing something.

**Comment by figureone** [comment]
Yeah, unfortunately we'll get flagged in the wordpress.org plugin repo if we allow arbitrary file inclusion, so that's a no-go. 

It's been awhile since I looked into the template stuff, but I think one of the relevant hooks is:
https://developer.wordpress.org/reference/hooks/type_template_hierarchy/
You might be able to use that one to add custom paths. Good luck!
